### ISSUE TITLE
Problem to use TFLMS2

### ISSUE THREAD

**Issue by adam-aph** [IBM/tensorflow-large-model-support#41]
Hi,
Thanks for this code, I hope it can help with my OOM problems on GPU. I have however few questions, because I'm not sure if I'm using it properly...
I have to use Tensorflow 1.x, so currently it is version 1.15.3 with big 6 layer CNN graph, which on the start allocates around 11 GB of GPU memory, and after 30 iterations the system dies because of OOM error. I used TFLMS2 branch because of TF 1.15, is that correct? I added following code to my program:
```python
       # initialize graph
        graph_manager.create_graph(task_parameters)

        try:
            from tensorflow_large_model_support import LMS
            lms = LMS(swapout_threshold=1, swapin_ahead=1, swapin_groupby=0)
            lms.batch_size = 512
            lms.run()
            logger.info("==== Large Model Support is Enabled! ====")
        except ModuleNotFoundError:
            logger.info("==== Large Model Support is not active! ====")
```
and in the logs I can see:
```
INFO:tensorflow:[LMS][0] No graph provided. LMS will use the default graph.
INFO:tensorflow:[LMS][0] Editing model for LMS
INFO:tensorflow:[LMS][0] The graph has 4180 vertices and 6222 edges.
INFO:tensorflow:[LMS][0] The graph has 444.5 MiB of learning parameters.
INFO:tensorflow:[LMS][0] The largest GPU operation is main_level/agent/main/online/gradients/main_level/agent/main/online/network_0/STEREO_CAMERAS/BatchnormActivationDropout_1_activation_grad/ReluGrad consuming 3.41 GiB
INFO:tensorflow:[LMS][0] Original categorized topological sort has 127 levels.
INFO:tensorflow:[LMS][0] LMS will use the following parameter set:
INFO:tensorflow:[LMS][0]   sync_mode: 0 (Asynchronous memory copy between host and device)
INFO:tensorflow:[LMS][0]   swapout_threshold: 1
INFO:tensorflow:[LMS][0]   swapin_ahead: 1 
INFO:tensorflow:[LMS][0]   swapin_groupby: 0 
INFO:tensorflow:[LMS][0] Added 598 operations to the model (156 swap-out operations (12.12 GiB) and 442 swap-in operations (66.96 GiB))
INFO:tensorflow:[LMS][0] Editing model for LMS, took: 934.6694946289062 ms
==== Large Model Support is Enabled! ====
```
Nevertheless, after about 30 iteraions it dies:
```
2020-06-06 14:55:20.542336: W tensorflow/core/common_runtime/bfc_allocator.cc:419] Allocator (GPU_0_bfc) ran out of memory trying to allocate 532.00MiB (rounded to 557842432).  Current allocation summary follows.
2020-06-06 14:55:20.542884: W tensorflow/core/common_runtime/bfc_allocator.cc:424] ***************__*****************************************************_*****************************
2020-06-06 14:55:20.542932: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at transpose_op.cc:198 : Resource exhausted: OOM when allocating tensor with shape[512,56,76,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
2020-06-06 14:55:30.543403: W tensorflow/core/common_runtime/bfc_allocator.cc:419] Allocator (GPU_0_bfc) ran out of memory trying to allocate 218.75MiB (rounded to 229376000).  Current allocation summary follows.
2020-06-06 14:55:30.543934: W tensorflow/core/common_runtime/bfc_allocator.cc:424] **********************************************************************_*****************************
2020-06-06 14:55:30.543977: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at conv_ops.cc:500 : Resource exhausted: OOM when allocating tensor with shape[512,128,25,35] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
2020-06-06 14:55:40.544135: W tensorflow/core/common_runtime/bfc_allocator.cc:419] Allocator (GPU_0_bfc) ran out of memory trying to allocate 218.75MiB (rounded to 229376000).  Current allocation summary follows.
2020-06-06 14:55:40.544719: W tensorflow/core/common_runtime/bfc_allocator.cc:424] **********************************************************************_*****************************
2020-06-06 14:55:40.544767: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at conv_ops.cc:500 : Resource exhausted: OOM when allocating tensor with shape[512,128,25,35] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
2020-06-06 14:55:50.544903: W tensorflow/core/common_runtime/bfc_allocator.cc:419] Allocator (GPU_0_bfc) ran out of memory trying to allocate 249.75MiB (rounded to 261881856).  Current allocation summary follows.
2020-06-06 14:55:50.545508: W tensorflow/core/common_runtime/bfc_allocator.cc:424] **********************************************************************_*****************************
2020-06-06 14:55:50.545544: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at transpose_op.cc:198 : Resource exhausted: OOM when allocating tensor with shape[512,27,37,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
{"simapp_exception": {"version": "2.0", "date": "2020-06-06 14:55:50.552782", "function": "training_worker", "message": "An error occured while training: 2 root error(s) found.\n  (0) Resource exhausted: OOM when allocating tensor with shape[512,56,76,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n\t [[{node main_level/agent/main/online/network_1/STEREO_CAMERAS/BatchnormActivationDropout_5_activation-0-0-TransposeNCHWToNHWC-LayoutOptimizer}]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\n\n\t [[main_level/agent/main/online/gradients/AddN_6/_627]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\n\n  (1) Resource exhausted: OOM when allocating tensor with shape[512,56,76,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n\t [[{node main_level/agent/main/online/network_1/STEREO_CAMERAS/BatchnormActivationDropout_5_activation-0-0-TransposeNCHWToNHWC-LayoutOptimizer}]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.\n\n0 successful operations.\n0 derived errors ignored.", "exceptionType": "training_worker.exceptions", "eventType": "system_error", "errorCode": "500"}}
simapp_exit_gracefully: simapp_exit--1
Terminating simapp simulation...
deepracer_racetrack_env - callstack=Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[512,56,76,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node main_level/agent/main/online/network_1/STEREO_CAMERAS/BatchnormActivationDropout_5_activation-0-0-TransposeNCHWToNHWC-LayoutOptimizer}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[main_level/agent/main/online/gradients/AddN_6/_627]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[512,56,76,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node main_level/agent/main/online/network_1/STEREO_CAMERAS/BatchnormActivationDropout_5_activation-0-0-TransposeNCHWToNHWC-LayoutOptimizer}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
```
Is there anything I should do differently to make LMS working? Any hints appreciated.
Thanks,
Adam

**Comment by adam-aph** [comment]
I found the problem - didn't see that graph has been edited after the session start, so all edits were ignored. After fixing the sequence it seems to work fine :)

**Comment by jayfurmanek** [comment]
Ok great. The usage of LMS is TF2 is a little easier since typically there are no sessions or precomputed graphs. Glad you got it working for you.
